### ISSUE TITLE
Keyword "node-red" in package json

### ISSUE THREAD

**Issue by ukmoose** [Wcctnoam/HadoopMQTTBridge#1]
As per the node-red docs http://nodered.org/docs/creating-nodes/packaging please don't include the keyword node-red until such time as the node is  stable and working correctly, and documented sufficiently for others to be able to use it.

You can still install on the command line without it while you test, but it hides the node from appearing in flows.node-red.org

**Comment by Wcctnoam** [comment]
I see. Sorry about that, I will immediately update it.
